ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,8 +11,8 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [18.x,20.x]
-        package: ['client', 'server']
+        node-version: [ 18.x,20.x ]
+        package: [ 'client', 'server' ]
 
     steps:
       - uses: actions/checkout@v3
@@ -24,12 +24,13 @@ jobs:
           cache: 'npm'
 
       - name: Install dependencies and run scripts
-        run: |
-          cd ${{ matrix.package }}
-          if [ ! -f package-lock.json ]; then
-            echo "package-lock.json not found in ${{ matrix.package }} directory!"
-            exit 1
-          fi
-          npm ci
-          npm test
-          npm run build --if-present
+        run: cd ${{ matrix.package }} && npm ci && npm test && npm run build --if-present
+        # run: |
+        #  cd ${{ matrix.package }}
+        #  if [ ! -f package-lock.json ]; then
+        #    echo "package-lock.json not found in ${{ matrix.package }} directory!"
+        #    exit 1
+        #  fi
+        #  npm ci
+        #  npm test
+        #  npm run build --if-present
